
# Preface

The intention of this effort is to provide an introduction to the area of credit-risk modelling to practitioners.

## Motivation

Most banks have procedures for rating the creditworthiness of their corporate and retail clients. This is necessity. The ratings published by rating agencies are usually available only for companies that have issued publicly traded debt. As a result, many small and medium-sized companies do not have credit ratings from rating agencies.

## Three risk factors

Credit risk is typically represented by means of three factors: default risk, loss risk and exposure risk:

### Default risk (PD)

**Default risk (PD)**: The default risk is the probability that a default event occurs. This probability is called the probability of default (PD). The probability has values between 0 and 1. There are many definitions of a default event. The most common definition of a default event is a payment delay of at least 3 months. Other definitions may add specific events.

In most cases, default risk is defined on a counterpart, not on a product. When a counterpart defaults on one loan or obligation, it is likely to default also on its other loans by the contamination principle. In particular asset classes, the contamination principle may not always hold and default risk can also be product specific.

In the case of a default, the actual loss depends on the loss given default (LGD) and the exposure at default (EAD).

### Loss risk (LGD)

**Loss risk (LGD)**: The loss risk determines the loss as a fraction of the exposure in the case of default. In the Basel II terminology, this parameter is known as the loss given default (LGD). In the case of no loss, the LGD is equal to zero. When one loses the full exposure amount, the LGD is equal to 100%. A negative LGD indicates a profit (e.g., due to penalty fees and interest rate). In some cases, the LGD can be above 100%, e.g., due to litigation costs and almost zero recovery from the defaulted counterpart. In some textbooks, one also uses the related concept of the recovery rate: the fraction of the total amount that one recovers. Both the loss given default and the recovery rate sum up to one.

The loss given default or recovery rate are not fixed parameters. These values fluctuate from one defaulted product to another. Some counterparts may cure from default and repay all the debt and delayed payments. For others, an agreement between the defaulted debtor and all the creditors may result in a distressed exchange agreement where all involved parties carry part of the loss. In the worst case, the default results in a bankruptcy procedure with high losses and the end of the bank–customer relation.

In practice, the LGD values are observed to vary quite a lot and depend upon the type of default and its resolution:

*Cure*: The financial health of the defaulted counterpart is cured shortly after the default event, e.g., because of an additional income or a shareholder intervention. The counterpart continues to fulfil its contractual obligations. There is no significant loss for the bank and the relation with the customer is not impacted.

*Restructuring*: The defaulted counterpart is able to recover from default after a debt restructuring, e.g., debt renegotiations resulting in a longer maturity and partial debt forgiveness. The bank–customer relation is damaged, but is often maintained. The bank accepts a medium loss to avoid higher losses in a liquidation or bankruptcy procedure.

*Liquidation*: The customer’s facilities are liquidated, collateral is seized. The relationship with the customer is ended. Liquidation procedures may involve high legal costs and losses are typically high.

It is difficult to predict the resolution type before default. On average, liquidation is expected to occur more for the weakest counterparts for which investors and banks are less eager to reinvest.

The LGD is measured on a product basis. It has typically values between 0 and 100% and is either represented in a continuous way or by means of loss grades.

### Exposure risk (EAD)

**Exposure risk (EAD)**: The exposure at the time of default (EAD) may not be known beforehand.


These risk factors also depend on the maturity of the contract. The longer the contract, the higher the uncertainty and the risk. In most applications one measures or expresses the credit risk on a 1-year horizon. The estimation, modelling and management of the default risk is the most developed. Both LGD and EAD risk received a lot of attention with the new Basel Capital Accord.
