
# Estimating Probability of Default

As explained regulators have for a long time required banks to keep capital for credit risk. Under Basel II banks can, with approval from bank supervisors, use their own estimates of default probabilities to determine the amount of capital they are required to keep. This has led banks to search for better ways of estimating these probabilities.

Default probability is the most critical and most intensely studied of the components of single‐name credit risk. Almost all firms that deal in credit risk instruments will want to form their own assessments of default probability (only if credit instruments are only a small portion of the investment portfolio and are almost all liquid might a fi rm be satisfi ed with just basing this assessment on input from an outside service). Firms with heavy investment in credit instruments, such as traditional banks, will devote considerable resources to their own determination of default probability.

## What is default?

PD is the probability that a firm will default in year t given that it did not default in year t − 1, all firms who have for the first time taken the loan (in any bank) in year t are excluded form the sample. Firms that were in the state of default for two or more consecutive years are also excluded and only their first migration to the state of default is taken into account.

Under the framework of Basel II the obligor defaults on his credit obligation if:

1. he is unlikely to pay the obligation or

2. is passed overdue more than 90 days (BCBS, 2006).

Since it is difficult to set the objective criteria for unlikeliness of paying the obligation, we derive the indicator of firm default from credit overdue. 

Defaulted firms are on average younger, have lower liquidity, higher leverage, lower cash flow, worse operating performance and have lower interest coverage, comparing to non-defaulted firms. A significantly useful indicator to separate between firms in default and non-default is also a variable which measures a number of days a firm has blocked bank account per year.

## Credit risk model architecture

1. Data Preparation

2. Variable Selection

3. Model Development

4. Model Validation

5. Calibration

6. Independent Validation

7. Supervisory Approval

8. Model Implementation : Roll out to users

9. Periodic Monitoring

10. Post Implementation Validation : Backtesting and Benchmarking

11. Model Refinement (if any issue)

## Rating Philosophy

Rating philosophy refers to the time horizon for which the ratings measure credit risk, and hence to how much they are influenced by cyclic effects

The first step in the rating model development process is the determination of the rating philosophy. Financial institutions should first decide what they want their models to indicate before developing them.

A rating philosophy is how the bank's obligor rating assignments are affected by the bank's choice of the range of economic, business, and industry conditions that are considered in the rating process (FED, 2006), in other words the kind of information the rating intends to summarize. Ratings can be stressed or unstressed with different stress levels. Rating system approaches may be characterized as being on a spectrum between:

1. Point-in-time (PIT) approaches - IFRS9

2. Through-the-cycle (TTC) approaches - Basel III


It refers to the time horizon for which ratings measure credit risk and how much they are influenced by cyclic effects.

This session will look at the challenges faced by financial institutions in developing their TTC PD models for retail portfolios

