
# Regulation

An agreement in 1988, known as the Basel Accord, marked the start of international standards for bank regulation. Since 1988, bank regulation has been an evoluntary process. New regulations have modified previous regulations, but often approaches used in previous regulations have been preserved. In order to understand the current regulatory environment, it is therefore necessary to understand historical developments.

This chapter explains the evolutioon of the regulatory environment.

Credit risk, the risk of loss due to a borrower being unable to repay a debt in full or in part, accounts for the bulk of most naks' risk-taking activities and regulatory capital requirements. There are two broad approaches to calculating RWAs for credit risk: the standardised approach and the internal ratins-based approach.

The initial interest in credit risk models originated from the need to quantify the amount of economic capital necessary to support a bank’s exposures

## The Basel Framework

### Basel I

### Basel II


Fore credit risk, Basel II  sprecified three approaches:

1. The Standardized Approach (SA)

2. The Foundation Internal Rating Based Approach (F-IRB)

3. The Advanced Internal Rating Based Approach  (A-IRB)

### The Standardized Approach

The standardized approach is used by banks that are not sufficiently sophisticated (in the eyes of regulators) to use the internal ratings approaches. The standardized approach is similar to Basel I  except for the calculation of risk weights (effect of credit risk of counterparty i.e. ratings is included.

Most banks around the world use the standardised approach (SA) for credit risk. Under this approach, supervisors set the risk weight that banks apply to their exposures to determine RWAs. This means that banks do not use their internal models to calsulate risk-weighted assets.

### The Foundation IRB Approach

The internal rating-based (IRB) approach for credit risk allows banks, under certain conditions, to use their internal models to estimate credit risk, and therefore RWAs. There are two main IRB approaches: Foundation Internal Rating Based (F-IRB) and Advanced Internal Rating Based (A-IRB).

Regulators base the capital requirement on the value at risk calculated using a one-year tune horizon and a 99.0% confidence level. They recognize that expected losses are usually covered by the way a financial institution prices its products, e.g. the interest charged by a bank on a loan is designed to recover expected loan losses. The capital required is therefore the value at risk minus the expected loss.

It has three credit risk parameters:


| Risk parameters | Description |
| ------         | ----------- |
| PD             | the probability thet the counterparty will default within one year (expressed as a decimal). |
| LGD            | the loss given default or the proportion of the exposure (expressed as a decimal).           |
| EAD            | the exposure at default (in euros).                                                          |

Banks develop own empirical model to estimate the probability of default (PD) for individual clients or groups of clients. Model needs to be approved by central bank. Banks are required to use regulators prescribed LGD or other parameters required for calculating the RWA for non-retail portfolio. For retail exposures banks are required to use their own estimates of the IRB parameters (PD, LGD, CCF).

Under foundation IRB, banks model only the probability of default. Under the advanced IRB approach, banks can also model their own loss given default (LGD) and exposure-at-default (EAD) levels.

The IRB approach is much more complex to implement bacause it requires stronger quantitative modelling skills within the bank, and access to historical default data.

Banks need three years of default data to build a PD model. Under advanced IRB, banks need five to seven years of data to build a LGD model. F-IRB uses regulatory LGD.

#### Probability of Default (PD)

Probability of Default (PD) is a financial term describing the likelihood of a default over a particular time horizon. It provides an estimate of the likelihood that a borrower will be unable to meet its dept obligations.

PD is used in a variety of credit analysses and risk management frameworks. Under Basel II it is a key parameter used in the calculation of economic capital or regulatory capital for a banking institution.

For public companites default probabilities are commonly estimated using either the "structural model" of credit risk (Morton, 1974)

#### Exposure at Default (EAD)



#### Loss given Default (LGD)


## IFRS


## Internal rating based on regulation

The Basel II Capital Accord explicitly promotes the use of internal ratings for risk management and capital requirements. It defines minimum requirements for internal rating systems. Bank’s internal rating systems used for regulatory capital purpose need to have two28 dimensions. The borrower dimension reflects the default risk. The facility dimension reflects default and loss risk combined in the expected loss or only loss risk when the bank estimates the loss internally.

The number of risk classes in each scale has to be such that a meaningful distribution across the different grades is obtained, avoiding excessive concentrations. The minimum number ofPD borrower grades is seven, where the grades should be such that the PD in a grade is sufficiently homogeneous. At least one grade should be used for the defaulted borrowers, although many banks use both an “unlikely to pay” and “default” grade. The prediction horizon for PD is one year, though ratings may be assigned on a longer time horizon. The use of TTC ratings is clearly preferred that assess the risk during adverse circumstances.

No minimum number of risk grades is required for LGD scales, but also the scale has to be meaningful and avoid large variations of LGD values in one singular scale. LGDvalues need to take into account economic downturn circumstances. The purpose of the accord is to improve risk management practices in banks towards a more unified use of ratings and towards comparable default and loss statistics.


The Basel Committee on Banking Supervision has communicated that it is the bank’s responsibility to understand and monitor its internal scoring systems.
